# Generated by Django 4.2.11 on 2024-05-22 18:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default='user', max_length=5)),
                ('username', models.CharField(default='username', max_length=30)),
                ('password', models.CharField(default='password', max_length=30)),
                ('budget', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1000000)])),
                ('user_hash', models.CharField(default='*****', max_length=5)),
            ],
        ),
    ]
