# Generated by Django 4.2.11 on 2024-05-26 19:13

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashback', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_hash', models.CharField(default='*****', max_length=5)),
                ('amount', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1000000)])),
                ('date_time', models.CharField(default=datetime.datetime(2024, 5, 26, 19, 13, 6, 488699), max_length=10)),
            ],
        ),
    ]
